name: antika_deposu
description: Antika Deposu mobile app for antique parts requests
publish_to: 'none'
version: 1.0.0+1
# Version 1.0.0 - Initial Release
environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  go_router: ^14.0.1
  http: ^1.2.1
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  intl: ^0.19.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/
